name: Run ClashForge and Upload Gist

on:
  workflow_dispatch:
  schedule:
    - cron: "02 16 * * *" # 每天运行一次

jobs:
  run-clashforge:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Cache Python dependencies
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Install dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run ClashForge script
    - name: Run ClashForge
      run: python ClashForge.py

    # Upload to Gist
    - name: Upload to Gist
      env:
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
      run: |
        GIST_ID="b04cdcc8b0bf842f7dc17bb4fcf31fe3"
        # 上传到指定 Gist
        if [ -f clash_config.yaml ]; then
          curl -X PATCH "https://api.github.com/gists/$GIST_ID" \
            -H "Authorization: token $GIST_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$(jq -n --arg content "$(cat clash_config.yaml)" '{files: {"FinalProxy.yaml": {content: $content}}}')"
        else
          echo "clash_config.yaml not found"
          exit 1
        fi
